class Api::V1::QuestionsController < Api::ApplicationController
    def index
        # curl http://localhost:3000/api/v1/questions
        questions = Question.order(created_at: :desc)
        # provide the each_serializer key to the options hash of the render method to specify which Serializer to use on each instance.
        render(json: questions, each_serializer: QuestionCollectionSerializer)
    end

    def show
        # curl http://localhost:3000/api/v1/questions/:id
        question = Question.find(params[:id])
        render(json: question)
    end

    def create
        question = Question.new(params.require(:question).permit(:title, :body, :tag_names))
        question.user = current_user
        if question.save
            render json: { id: question.id }
        else
            render(
                json: { errors: question.errors },
                status: 422 # unprocessable entitiy HTTP Status Code
            )
        end
    end

    def destroy
    end
end












# Generated by: rails g controller api::v1::questions --no-assets --no-helper
